import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo edited by Alim ',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: const Color.fromARGB(255, 62, 183, 58)),
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  Widget _recContainer(int colorSeed) {
  // 1. Условие выхода из рекурсии (остановка)
  if (colorSeed <= 0) {
    return const SizedBox.shrink(); // Возвращаем пустой виджет в конце
  }

  double seed = colorSeed.toDouble();

  return Container(
    // Ограничиваем значения цвета от 0 до 255 с помощью .clamp()
    color: Color.fromARGB(
      255, 
      (235 - colorSeed).clamp(0, 255), 
      (0 + colorSeed).clamp(0, 255), 
      0
    ),
    width: (100 - seed).clamp(0, 100), 
    height: (50 - seed).clamp(0, 50),
    transform: Matrix4.rotationZ( (0.2-seed).clamp(-0.3, 2) ),
    // 2. Правильный вызов вложенного виджета
    child: _recContainer(colorSeed - 10), 
  );
}

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),

      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('Hello world, below is containers generated by recusrion. Made by Alimtair Lab 1'),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
            _recContainer(40)
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
